version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    environment:
      DEBIAN_FRONTEND: noninteractive
      DOCKER_BUILDKIT: 1
    init: true
    ports:
      - "22:22"
    security_opt:
      - seccomp:unconfined
    volumes:
      - app_volume:/workspace
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  app_volume:
